import Nav from "@/components/Nav";
import "./globals.css";

import { JetBrains_Mono } from "next/font/google";
import { DataProvider } from "@/context/dataContext";
import { ToastContainer } from "react-toastify";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  variable: "--font-jetbrains",
});

export const metadata = {
  title: "HeroVault",
  description: "Generated by CodeHasib",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className={`${jetbrainsMono.variable}`}>
        <DataProvider>
          <Nav></Nav>
          {children}
        </DataProvider>
        <ToastContainer></ToastContainer>
      </body>
    </html>
  );
}
